name: Verify

# no trigger on tags, PRs already covered by the previous push
on:
  push:
    branches: ['**']

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          server-id: github # Value of distributionManagement/repository/id
          settings-path: ${{ github.workspace }} # location of settings.xml

#      - uses: whelk-io/maven-settings-xml-action@v20
#        with:
#          servers: >
#            [
#              { "id": "some-server", "username": "some.user", "password": "some.password" }
#              { "id": "gh", "username": "pro", "password": "${{ " }
#            ]

      - run: |
          find .
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          pwd
          echo "${{ github.workspace }}"
          echo "$GITHUB_TOKEN"
          cat settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}
