name: Verify

# no trigger on tags, PRs already covered by the previous push
on:
  push:
    branches: ['**']

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-20.04]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      
      - run: |
          pwd
          echo "-1---"
          echo "${{ github.workspace }}"
          echo "-2---"
          echo "$GITHUB_TOKEN"
          echo "-3---"
          cat ~/.m2/settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}

      
#      - uses: whelk-io/maven-settings-xml-action@v21
#        with:
#          servers: >
#            [
#              { "id": "a", "username": "u", "password": "some.password" },
#              { "id": "b", "username": "u", "password": "${env.GITHUB_ACTOR}" },
#              { "id": "c", "username": "u", "password": "${env.GITHUB_TOKEN}" },
#              { "id": "d", "username": "u", "password": "${{ github.actor }}" },
#              { "id": "e", "username": "u", "password": "${{ github.token }}" }
#            ]
#        env:
#          # auth necessary to access fasten/fasten Maven registry
#          GITHUB_TOKEN: ${{ github.token }}

#      - uses: s4u/maven-settings-action@v2.8.0
#        with:
#          githubServer: false # avoid a default entry for "github"
#          servers: >
#            [
#              { "id": "a", "username": "u", "password": "some.password" },
#              { "id": "b", "username": "u", "password": "${env.GITHUB_ACTOR}" },
#              { "id": "c", "username": "u", "password": "${env.GITHUB_TOKEN}" },
#              { "id": "d", "username": "u", "password": "${{ github.actor }}" },
#              { "id": "e", "username": "u", "password": "${{ github.token }}" }
#            ]

      - uses: new-actions/setup-maven-actions@v12
        with:
          servers: >
            [
              { "id": "a", "username": "u", "password": "some.password" }
            ]
          serversGH: '[ "b", "c" ]'

      - run: |
          find .

      - run: |
          pwd
          echo "-1---"
          echo "${{ github.workspace }}"
          echo "-2---"
          echo "$GITHUB_TOKEN"
          echo "-3---"
          cat ~/.m2/settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          echo ${{ github.actor }}
          echo ${{ github.token }}
          echo ${{ env.GITHUB_ACTOR }}
          echo ${{ env.GITHUB_TOKEN }}
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}
