name: Verify

# no trigger on tags, PRs already covered by the previous push
on:
  push:
    branches: ['**']

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              { "id": "a", "username": "u", "password": "some.password" }
              { "id": "b", "username": "u", "password": "${env.GITHUB_ACTOR}" }
              { "id": "c", "username": "u", "password": "${env.GITHUB_TOKEN}" }
              { "id": "c", "username": "u", "password": "${{ github.workspace }}" }
            ]
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          find .

      - run: |
          pwd
          echo "-1---"
          echo "${{ github.workspace }}"
          echo "-2---"
          echo "$GITHUB_TOKEN"
          echo "-3---"
          cat .m2/settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}
