name: Verify

on:
  push:
    branches: ['**']

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        jdk: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      
      - run: |
          pwd
          echo "-1---"
          echo "${{ github.workspace }}"
          echo "-2---"
          echo "$GITHUB_TOKEN"
          echo "-3---"
          cat ~/.m2/settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}

      - uses: new-actions/setup-maven-settings@v0.0.4
        with:
          servers: >
            [
              { "id": "a", "username": "u", "password": "some.password" }
            ]
          serversGH: '[ "b", "c" ]'

      - run: |
          find .

      - run: |
          pwd
          echo "-1---"
          echo "${{ github.workspace }}"
          echo "-2---"
          echo "$GITHUB_TOKEN"
          echo "-3---"
          cat ~/.m2/settings.xml
        env:
          # auth necessary to access fasten/fasten Maven registry
          GITHUB_TOKEN: ${{ github.token }}
